name: loading_more_list_library
description: dart package library for LoadingMoreList, it provides core classes.
version: 2.0.3
homepage: https://github.com/fluttercandies/loading_more_list_library

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  fast_immutable_collections: ^9.0.0
  meta: ^1.9.0


