name: loading_more_list_library
description: dart package library for LoadingMoreList, it provides core classes.
version: 2.0.1
homepage: https://github.com/fluttercandies/loading_more_list_library

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fast_immutable_collections: ^8.1.1
  meta: ^1.8.0


